// agência -> assistência, for Bahia. Generated by
// scripts/gen-assistencias.R from orcedata::assistencias_ba — do not
// edit by hand.
//
// The 2025 R report grouped its assistência sheets through this same
// mapping (R/report.R:103). Vendored rather than fetched: it is reference
// data that changes only by administrative act.
(function () {
  'use strict';

  if (window.__municProAssistencias) return;

  const ASSISTENCIA_POR_AGENCIA = {
    '290070200': 'Alagoinhas',
    '290320100': 'Guanambi',
    '290390400': 'Guanambi',
    '290460500': 'Guanambi',
    '290490200': 'Alagoinhas',
    '290570100': 'Salvador',
    '290790500': 'Jeremoabo',
    '290840800': 'Jeremoabo',
    '290980200': 'Alagoinhas',
    '291060200': 'Alagoinhas',
    '291070100': 'Jeremoabo',
    '291072700': 'Vitória da Conquista',
    '291080000': 'Alagoinhas',
    '291170900': 'Guanambi',
    '291320000': 'Senhor do Bonfim',
    '291360600': 'Vitória da Conquista',
    '291390300': 'Alagoinhas',
    '291400000': 'Alagoinhas',
    '291460400': 'Senhor do Bonfim',
    '291470300': 'Senhor do Bonfim',
    '291480200': 'Vitória da Conquista',
    '291560100': 'Vitória da Conquista',
    '291640100': 'Vitória da Conquista',
    '291750800': 'Senhor do Bonfim',
    '291760700': 'Guanambi',
    '291800100': 'Guanambi',
    '291810000': 'Jeremoabo',
    '291840700': 'Senhor do Bonfim',
    '291950400': 'Guanambi',
    '292170800': 'Senhor do Bonfim',
    '292400900': 'Jeremoabo',
    '292510500': 'Vitória da Conquista',
    '292530300': 'Vitória da Conquista',
    '292600400': 'Senhor do Bonfim',
    '292630100': 'Jeremoabo',
    '292660800': 'Jeremoabo',
    '292740800': 'Salvador',
    '292740801': 'Salvador',
    '292810900': 'Guanambi',
    '292840600': 'Guanambi',
    '292860400': 'Salvador',
    '292870300': 'Alagoinhas',
    '292920600': 'Salvador',
    '292990900': 'Senhor do Bonfim',
    '293010500': 'Senhor do Bonfim',
    '293050100': 'Jeremoabo',
    '293135000': 'Vitória da Conquista',
    '293290300': 'Alagoinhas',
    '293330700': 'Vitória da Conquista',
    '293360400': 'Senhor do Bonfim',
  };

  // Falls back to the agência's own name when the código is unknown, so a
  // new agência shows up under a visible label instead of vanishing from
  // the grouping or collapsing into a blank row.
  function assistenciaDe(agenciaCodigo, agenciaNome) {
    return ASSISTENCIA_POR_AGENCIA[String(agenciaCodigo)] ||
      `(sem assistência) ${agenciaNome || agenciaCodigo}`;
  }

  window.__municProAssistencias = { ASSISTENCIA_POR_AGENCIA, assistenciaDe };
})();
