#!/usr/bin/env Rscript
# Regenerates extension/common/assistencias.js from orcedata::assistencias_ba.
#
# The mapping (50 agências -> 6 assistências in Bahia) is reference data that
# changes only by administrative act, so it is vendored as a JS object rather
# than fetched. Committing the generator means it can be refreshed when
# orcedata updates, instead of being a mystery blob.
#
# Note: this lived in `orce` in the 2025 R package (R/report.R:103); it has
# since moved to `orcedata`.
#
# Run from the repo root:  Rscript scripts/gen-assistencias.R
suppressMessages({
  library(orcedata)
  library(dplyr)
})

d <- orcedata::assistencias_ba |>
  dplyr::arrange(agencia_codigo)

entries <- paste0(
  "    '", d$agencia_codigo, "': '", d$assistencia_nome, "',"
)

lines <- c(
  "// agência -> assistência, for Bahia. Generated by",
  "// scripts/gen-assistencias.R from orcedata::assistencias_ba — do not",
  "// edit by hand.",
  "//",
  "// The 2025 R report grouped its assistência sheets through this same",
  "// mapping (R/report.R:103). Vendored rather than fetched: it is reference",
  "// data that changes only by administrative act.",
  "(function () {",
  "  'use strict';",
  "",
  "  if (window.__municProAssistencias) return;",
  "",
  "  const ASSISTENCIA_POR_AGENCIA = {",
  entries,
  "  };",
  "",
  "  // Falls back to the agência's own name when the código is unknown, so a",
  "  // new agência shows up under a visible label instead of vanishing from",
  "  // the grouping or collapsing into a blank row.",
  "  function assistenciaDe(agenciaCodigo, agenciaNome) {",
  "    return ASSISTENCIA_POR_AGENCIA[String(agenciaCodigo)] ||",
  "      `(sem assistência) ${agenciaNome || agenciaCodigo}`;",
  "  }",
  "",
  "  window.__municProAssistencias = { ASSISTENCIA_POR_AGENCIA, assistenciaDe };",
  "})();"
)

writeLines(lines, "extension/common/assistencias.js")
cat("wrote extension/common/assistencias.js —", nrow(d), "agências,",
    length(unique(d$assistencia_nome)), "assistências\n")
